version: '3'

services:
  db:
    image: postgres # Por padrão já expõe a porta 5432 pros outros containers
    volumes:
      - calendarium_data:/var/lib/postgresql/data

  back:
    build: ./django
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Chave de segurança geral do Django
      CALENDARIUM_SECRET_KEY: "chave-de-segurança-secreta"
      # Variáveis do DB
      CALENDARIUM_DB_NAME: "postgres"
      CALENDARIUM_DB_USER: "postgres"
      CALENDARIUM_DB_PASSWORD: "password"

  front:
    build: ./angular
    command: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - ./angular/:/code
    depends_on:
      - back

volumes:
  calendarium_data:
    driver: local
