version: '3'

services:
  db:
    image: postgres # Por padrão já expõe a porta 5432 pros outros containers
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build:
      context: ../../django
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # Chave de segurança geral do Django
      CALENDARIUM_SECRET_KEY: "chave-secreta"
      # Variáveis do DB
      CALENDARIUM_DB_NAME: "postgres"
      CALENDARIUM_DB_USER: "postgres"
      CALENDARIUM_DB_PASSWORD: "password"

  front:
    build:
      context: ../../angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./angular/:/app
      - /app/node_modules
    depends_on:
      - back

volumes:
  postgres_data:
    driver: local
