version: '3'

services:
  db:
    image: postgres:10.3-alpine # Por padrão já expõe a porta 5432 pros outros containers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default
    labels:
      traefik.enable: "false"

  back:
    build:
      context: ../../django
      dockerfile: Dockerfile.prod
    networks: 
      - default
      - proxy
    labels:
      traefik.backend: back
      traefik.frontend.entryPoints: http, https
      traefik.frontend.rule: Host:service.calendarium.jeffersonbc.com
      traefik.docker.network: proxy
      traefik.port: "8000"
    depends_on:
      - db
    environment:
      # Chave de segurança geral do Django
      CALENDARIUM_SECRET_KEY: "chave-secreta"
      # Variáveis do DB
      CALENDARIUM_DB_NAME: "postgres"
      CALENDARIUM_DB_USER: "postgres"
      CALENDARIUM_DB_PASSWORD: "password"

  front:
    build:
      context: ../../angular
      dockerfile: Dockerfile.prod
    networks: 
      - proxy
    labels:
      traefik.backend: front
      traefik.frontend.entryPoints: http, https
      traefik.frontend.rule: Host:calendarium.jeffersonbc.com
      traefik.docker.network: proxy
      traefik.port: "80"
    depends_on:
      - back

volumes:
  postgres_data:
    driver: local

networks: 
  proxy:
    external: true
